from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="ml-cli-tool",
    version="0.1.0",
    author="Atunrase Ayomide",
    author_email="atunraseayomide@gmail.com",
    description="A CLI tool for machine learning workflows",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/Ayo-Cyber/ml_cli",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    install_requires=[
        "setuptools>=65.0.0",
        "pandas",
        "click>=8.0.0,<9.0.0",
        "rich-click>=1.6.0,<2.0.0",
        "pyyaml>=6.0.0,<7.0.0",
        "questionary>=1.10.0,<3.0.0",
        "tqdm>=4.60.0,<5.0.0",
        "rich>=12.0.0,<14.0.0",
        "numpy",
        "configparser>=5.0.0,<8.0.0",
        "python-dotenv>=0.19.0,<2.0.0",
        "requests>=2.25.0,<3.0.0",
        "pytest>=7.0.0,<9.0.0",
        "psutil>=5.8.0",
        "fastapi>=0.100.0,<1.0.0",
        "uvicorn>=0.20.0,<1.0.0",
        "scikit-learn>=1.1.0,<2.0.0",
        "joblib>=1.1.0,<2.0.0",
        "tpot",
        "matplotlib>=3.5.0,<4.0.0",
        "seaborn>=0.11.0,<1.0.0",
        "python-multipart>=0.0.5",
        "gunicorn>=20.1.0",
        "Jinja2>=3.0.0,<4.0.0",
        "itsdangerous>=2.0.0,<3.0.0",
        "python-dotenv>=0.19.0,<1.0.0",
        "passlib>=1.7.0,<2.0.0",
        "bcrypt>=3.2.0,<5.0.0",
        "SQLAlchemy>=1.4.0,<3.0.0",
        "psycopg2-binary>=2.9.0,<3.0.0",
        "alembic>=1.7.0,<2.0.0",
        "greenlet>=1.1.0,<4.0.0",
        "pydantic-settings>=2.0.0,<3.0.0",
        "certifi>=2021.0.0",
        "pyarrow",
    ],
    entry_points={
        "console_scripts": [
            "ml=ml_cli.cli:cli",
        ],
    },
    python_requires=">=3.10",
)
